### ISSUE TITLE
2018年8月迭代计划

### ISSUE THREAD

**Issue by starlying** [siteserver/cms#1138]
这个计划包含我们2018年八月份的工作。这是一个4周的迭代计划，我们将在9月1日号发布 SiteServer CMS V6.6 正式版。

> **提示：** 此文档会在本月持续修订，新发现的bug以及需要完善的功能会实时更新至此文档。

> **提示：** 此文档中列举的项目只表示我们承诺会实现且优先安排，并不代表本月迭代能够全部实现。

## 计划安排
2018-09-01：发布 SiteServer CMS 6.6 正式版

## 《STL 语言参考手册》

* [x] 重写组织手册结构
* [x] 与最新版本系统标签与属性一一对应
* [x] 增加STL示例代码

## REST API 增强

* [x] 支持列表翻页，能够设置每页返回数量
* [x] 支持内容搜索，能够支持任意字段搜索，同时支持精确搜索与模糊搜索
* [x] 支持内容列表根据orderBy参数进行排序

## Cli 命令行增强

* [x] 新增一键安装系统命令：install
* [x] 修复SQLServer 2008版本Bug，支持导出、升级与导入
* [x] 优化命令行执行参数

## STL 解析增强

* [x] 新增stl:channels、stl:contents列表实体解析为JSON数组功能
* [x] 新增stl:channel、stl:content实体解析为JSON对象功能
* [x] 强化replace和to属性，支持数组替换和正则表达式替换
* [x] 新增stl:container切换上下文功能
* [x] 修复pageSqlContents列表问题

## BUG修复

* [x] ORACLE SS.GovInteract 和SS.GovPublic ORA-00001: 违反唯一约束条件 #879
* [x] ORACLE 点击内容审核和内容回收站: 列表中的最大表达式数为 1000 #878
* [x] ORACLE 管理员管理---权限设置，然后分配角色，报错。 #903
* [x] 错误! 内容修改失败：Data too long for column 'ContentIdCollection' at row 1 #1090
* [x] Server Error in Application 值不能为 null。参数名: key #1188
* [x] 在分类设置里面添加分类后内容筛选下面没有任何内容 #1008
* [x] 属性中&符号自动转义 #1185
* [x] pageSqlContents查询不出数据来 #1198 
* [x] 后台查看互动交流的办件时出错 #1202
* [x] 插入视频时取消选择自动播放没有效果 #1239
* [x] 登录页面验证码不过期，可以根据返回内容不同，进行用户探测 #1244
* [x] 包含文件管理查看链接地址不对 #1234 

## 功能增强

* [x] ORACLE 系统站点管理下的站点树和web访问地址站点树，不一致。 #880
* [x] stl:dynamic标签添加JavaScript回调函数 #1031
* [x] API请求，属性请求加强 #1131

## 待验证
* [x] focusviewer标签6.5的版本现在可以用吗？ #1252

## 贡献

感谢以下用户提交代码，帮助我们改进 SiteServer CMS ：

@fenguo11：stl:dynamic类标签添加JavaScript回调函数 #1031

**Comment by jsonluo2018** [comment]
还是没有看见.net core的东西。也没有看到去webform 的具体时间

**Comment by jsonluo2018** [comment]
还是没有看见.net core的东西。也没有看到去webform 的具体时间

**Comment by zfnet0591** [comment]
用户中心注册表单自定义也没有

**Comment by zzj19930721** [comment]
加油哦

**Comment by goofy74** [comment]
赞，感谢付出。

**Comment by xiaoxh266** [comment]
stl:contents列表实体怎样在实际项目中使用啊
