### ISSUE TITLE
2018年9月/10月迭代计划

### ISSUE THREAD

**Issue by starlying** [siteserver/cms#1280]
这个计划包含我们2018年9月/10月的工作。这是一个8周的迭代计划，我们将在11月1日号发布 SiteServer CMS V6.7 正式版。

> **提示：** 此文档会在本月持续修订，新发现的bug以及需要完善的功能会实时更新至此文档。

> **提示：** 此文档中列举的项目只表示我们承诺会实现且优先安排，并不代表本月迭代能够全部实现。

## 计划安排
2018-11-01：发布 SiteServer CMS 6.7 正式版

## 内容表更新

新版本简化了网站内容表的设计，创建站点时可以选择使用现有的内容表、新建站点内容表或者手动输入表名称，从而实现了站点和数据库中存储内容的表的快速关联。

新版本新增或者修改内容表字段将变得非常简单直接，进入对应的数据库管理工具，在管理工具中对内容表进行字段新增或者编辑操作，再进入 SiteServer CMS 后台清除缓存，既可以完成内容表字段的维护。

如果新建或者编辑站点时手动输入内容表，系统将检测表名是否存在，如果存在将使用指定的表，如果不存在，系统将创建对应的内容表。

## 用户中心、用户投稿

由于之前用户中心反馈的问题比较多，我们在本次迭代中彻底重新开发了用户中心以及用户投稿功能，实现了用户自定义字段、注册权限控制以及用户组功能，同时新的用户中心采用全新的用户界面，将完全支持手机端访问。

## BUG修复

* [ ] 跨站点复制新闻内容时正文中的图片没有跨站点复制过去 #1305
* [x] 提交表单正则规则验证不起作用 #253 #338
* [x] 【表单】批量新增字段无效、导入、导出功能无效。  #181
* [x] 【用户中心】点击账号安全下的立即修改出现404。  #187
* [ ] 【投票】后台勾选提交投票者信息，前台页面没有显示  #190
* [x] 用户中心不能绑定手机和邮箱，显示未开通  #331
* [x] 自定义表单标题为空后无法编辑 #552
* [x] 表单插件，新增一个表单然后点击自定义模版，再点返回报错 #555
* [ ] 图片删除的时候应该把相应物理路径的图片一起删除 [#4](https://github.com/siteserver/SS.Photo/issues/4)。
* [ ] 投票字段管理，复选列表,单选列表,下拉列表,---快速设置失效。 #1123 
* [x] Server Error in Application Object reference not set to an instance of an object. #1235
* [x] Server Error in Application ORA-00001: 违反唯一约束条件 (CMS.PK_SS_GOVINTERACT_CHANNEL_ID) #1268
* [ ] ss.login 插件bug，安装后解析stl:login标签，显示缺少template.html #1311
* [ ] 角色分配给管理员时，一个账号一个角色没有问题，一个账号多个角色有问题 #1327 
* [ ] 发现BUG一枚 #1333
* [ ] 站点之间的栏目或内容转移图片路径问题。 #1346
* [ ] 互动交流插件BUG #1348
* [x] 提交表单字段验证规则EMAIL格式不起作用，最短字数不起作用，其它没试 #1351
* [ ] /api/pages/settings/adminAccessTokens?&1536654977155 #1332
* [x] gulp build 报错 #1357
* [ ] 互动交流 设置为 不公开， 为什么前台还是公开的？ #1372
* [ ] 翻页实体标签TotalNum失效了 #1306
* [ ] 在内容模板中，将文章内容设置成分页 #1383
* [x] Server Error in Application 对已关闭对象的操作无效 #1391
* [x] <stl:login></stl:login>在 “STL在线解析” 里面解析报错 #1392
* [x] ORA-12570: 网络会话: 意外的数据包读取错误 #1398
* [x] 用户中心 下的投稿中心一些问题。 #1401
* [ ] 互动交流栏目如何调用答复内容 #1411
* [x] 6.6.19以后的版本生成有问题 #1412
* [ ] 引用内容不同步 #1443
* [x] 模版匹配失效。 #1457

## 功能增强

* [x] 站点列表与系统头部的选择站点排序不一致 #1303
* [ ] 建议模板列表页搜索功能加上搜索提示，显示可能的模板 #985
* [ ] 优化用户中心加载速度 #1003
* [ ] 后台用户管理应该显示用户头像 #1103
* [ ] 文章url地址增加按guid来生成 #1101 
* [ ] stl:if 判断自定义内容 #1135 
* [ ] 字段设置中内置字段的“添加”建议改成“修改” #1148 
* [ ] 后台内容搜索的目标字段没有“内容” #1157 
* [ ] API附加字段取值建议 #1161
* [ ] 模板点击修改后应该返回之前的列表 #1180 
* [ ] 在html编辑状态修改后点“确定”不会保存 #1181 
* [ ] 一个星期内有登录自动顺延 #1201
* [ ] stl:if 支持testOperate="startsWith"判断字符开始 #1248
* [x] 生成页面时栏目太多，导致很难选到需要的栏目，建议修改成可伸缩的选中方式 #1291
* [ ] 建议！在用户注册的时候，可以选择用户组，方便分类发布投稿 #1287 
* [ ] 在后台的在线编辑器里插入视频后 如何进行循环播放设置 #1296
* [ ] 生成单页模板特别多，建议可以设置单页文件夹，将文件夹内的单页统一生成 #1309
* [x] 建议登录页面用户名密码错误时刷新验证码 #1334
* [ ] API的trigger地址可以跳转到站外页面 #1373
* [ ] 关于生成管理下的一键生成的建议 #1400
* [ ] 关于 用户投稿设置 里面 关联用户 问题。 #1399 

## 待验证

* [x] 用户中心投稿栏目能不能在后台进行设置？ #1049 
* [ ] 导入word生成html BUG，一些文档保存不了。 #1018
* [ ] 用户中心问题 #1150
* [ ] Server Error in Application 未将对象引用设置到对象的实例。 #1163
* [ ] 新版本无法读取站点模板，版本号：Siteserver-6.5.1.0 #1160 
* [ ] 相册插件，想加图片，出现这个提示 #1212
* [ ] 图片同步问题 #1240 
* [ ] <stl:search>当搜索关键词为空的时候，怎么不显示内容啊？ #1253 
* [ ] Table 'xxxxxxx.siteserver_table' doesn't exist #1275
* [ ] SS.Photo 插件找不到方法 #1314
* [ ] 6.6.1版本，内容变动，引用内容无变化不同步 #1325 
* [ ] 提交表单在点击回复时不出现编辑器无法编辑 #1340
* [ ] 更新10天内内容以红色突出无效 #1347
* [ ] 互动交流无法提交表单 #1344
* [ ] 6.6.20-beta 生成页面有问题 #1358
* [ ] 插件ss:poll生成问题 #1362
* [ ] 使用新增内容API添加内容时，远程服务器返回错误: (500) 内部服务器错误 #1389

## 贡献

感谢以下用户提交代码，帮助我们改进 SiteServer CMS ：

@zzj19930721 ：新增后台-栏目页排序（仿内容页） #1425

**Comment by starlying** [comment]
.net core 和 去ASPX一直在进行中，这个没有放到日程里面，每个月都有一批aspx转成cshtml。

**Comment by zzj19930721** [comment]
加油

**Comment by rantilin** [comment]
加油，一直关注着.net的发展，虽然转PHP去了

**Comment by zhangyq158** [comment]
建议在注册的时候，可以选择已经在后台已经设置好的用户组，因为每个用户组的权限不一样，不同用户组。可以在不同权限下投稿，而不必在后台，由管理员再重新分组，注册用户数量大的时候，没办法管理

**Comment by starlying** [comment]
好的，我们会增加一个设置，可以开启或关闭用户注册的时候前台用户组选择功能 @zhangyq158

**Comment by zfnet0591** [comment]
用户注册表单 字段自定义 啥时列入计划呀

**Comment by skotbenben** [comment]
商城插件啥时候有文档啊？还有，建议增加用户组！！感谢开发团队的付出！

**Comment by skotbenben** [comment]
补充一下楼上：我所说的用户组不是目前后台的管理用户组和角色。是VIP0、vip1这种自定义用户组。只与前端阅读、下载等权限有关的。

**Comment by smallrain3** [comment]
说实在的，我比较关心的是net core版本什么时间可以上线...

**Comment by zzj19930721** [comment]
@skotbenben  
1.后台有用户组模式，建了以后，然后用stl:sql去操作也行，目前我是这样。
2.然后你在开发商城吗？一起？

**Comment by HillCat** [comment]
不知道是否能够支持动态页面。

**Comment by cuiguorui** [comment]
怎么实现增加论坛模块？5.0版本的论坛怎么加在6.7版本上？

**Comment by jackieleecn** [comment]
加油！！觉得SS越来越棒了！！！

**Comment by chenth11111** [comment]
请问6.7版本的，缓存会影响计数器在前端页面不能实时显示,数据库里的hits明明有增加，但前端没有显示增加，后台系统管理-实用工具-清空缓存，它就显示最新的了。这是个bug吗？

**Comment by KevinPan** [comment]
希望有用户登录留言的插件
