### ISSUE TITLE
2018年11月/12月迭代计划

### ISSUE THREAD

**Issue by starlying** [siteserver/cms#1521]
欢迎来到2018年11月1日发布的SiteServer CMS 新版本 V6.8，经过两个月的连续迭代开发，V6.8 版本新增了几项重要功能，我们希望你会喜欢，一些关键的亮点包括：

## .NET Core 平台迁移

SiteServer CMS 基于.NET Framework，只能运行在Windows系统下，2018年产品开发团队不断改造产品架构，逐步向.NET Core 平台迁移，截止到V6.8版本，系统框架已经基本迁移至.NET Core兼容的依赖包中，目前剩余需要向.NET Core 平台迁移的部分主要是Web Form页面，预计2019年上半年可以彻底完成.NET Core 平台迁移工作。

向.NET Core 平台迁移完成后，系统能够利用.NET Core跨平台的优势实现在Linux系统中部署，或者通过容器的方式部署，性能和可伸缩性将显著增强。 借助 ASP.NET Core，系统运行的服务器/虚拟机 (VM) 数要低得多，减少服务器/VM 后可节省基础结构和托管成本。

## 与官网插件、模板集成

新版本中能够安装和使用的插件以及站点模板将与SiteServer CMS官网紧密集成，管理员在后台界面中创建站点时可以方便地选择合适的模板，一键生成网站，或者通过后台一键安装、升级插件。

经过改版，SiteServer CMS官网中的插件以及模板不再仅限于官方发布，任何开发人员或者企业均可以在官网注册账号上传并发布自己的模板及插件，随着SiteServer CMS用户量的不断增加，相信会有更多的开发人员愿意开发出精美的模板以及强大的插件，通过产品与官网的集成，能够让这些模板与插件更方便地到达最终用户的系统中。

## 依申请公开插件

伴随6.8版本，我们发布了[依申请公开插件](http://www.siteserver.cn/plugins/plugin.html?id=SS.Application)，用于实现行政机关根据公民、法人或者其他组织的申请，依照法律规定和本机关的职权，向申请人公开信息的功能。

![01 1](https://user-images.githubusercontent.com/4256611/50584318-ccd0ab00-0ea9-11e9-9319-f71cde5c44ed.png)

插件使用请参考： [插件使用文档](http://plugins.siteserver.cn/ss.application/#/)

## 插件文档增强

![qq 20190102162159](https://user-images.githubusercontent.com/4256611/50584592-719fb800-0eab-11e9-8342-1666ae6ba8ee.png)

之前，由于各个插件处于快速迭代开发中，相关使用文档及模板标签说明一直比较欠缺，在2018年11月/12月迭代周期中，我们逐步完善了部分插件使用文档及标签调用说明。

在接下来几个开发周期中，我们将集中力量把仍未发布使用手册的插件文档补齐，让用户在使用任何插件的时候能够查阅详细的插件使用说明、操作手册以及模板标签调用说明。

### 完善后台框架页（main页面）打开速度及用户体验

新版本将pageMain.aspx页面修改为main.cshtml，由原来传统的WebForm方式改为Razor页面，统一由Vue管理页面布局，使得加载速度有明显提升。

### 后台手机端支持增强

新版本完善了通过手机端访问后台时的菜单导航，同时优化了手机端小屏幕尺寸环境下后台默认页面的展现方式，使得手机端访问后台更加舒适。

### 完善创建站点方式，增强在线模板选择界面

新版本增强了在线站点模板选择功能，使得创建网站前对在线模板的筛选和预览更加便捷

![qq 20190103052007](https://user-images.githubusercontent.com/4256611/50613053-43f05880-0f17-11e9-91de-b0835b197184.png)

### 其他功能增强：

* [x] 新增一键取消生成功能，避免多次重复生成。
* [x] 后台头部站点列表以最后一次管理站点的时间进行排序，点击全部站点以实际站点排序进行显示，方便站点管理的切换。
* [x] 完善添加插件界面，与官网插件频道集成。
* [x] 新增管理员头像功能，更易于识别。
* [x] REST API中contents接口新增按多个栏目列出内容列表选项。
* [x] 完善判断内容是否图片内容标签的写法（stl:if type="imageUrl"，原始写法为stl:if type="imageUrl" op="NotEmpty"）。

## BUG修复

* [x] 火狐添加内容点击无效，63.0.1版本的火狐。 #1581
* [x] 创建专题页Server Error in Application 未将对象引用设置到对象的实例。 #1606
* [x] 通过【添加栏目】按钮无法添加栏目 #1541
* [x] 内容表AddUserName对应的原来是displayName，现在怎么变成username了 #1550
* [x] 新增字段Server Error in Application 未将对象引用设置到对象的实例。 #1559 
* [x] 修改已创建的站点内容表，选择失效。 #1557
* [x] 新版本编辑器，栏目内容无法上传图片 #1547
* [x] <stl:contents>标签带条件时startNum不起作用 #1539
* [x] 管理员填写手机号，安装成功以后，登录不上 #1535
* [x] 缓存会影响计数器在前端页面不能实时显示 #1528
* [x] 修正以“引用地址”方式转移内容后，目的栏目不进行生成 #1563
* [x] <stl:select> BUG 解析不出来标题和外链，只解析了他自己的连接。 #1494 
* [x] ss.login 插件bug，安装后解析stl:login标签，显示缺少template.html #1311 

## 贡献

感谢以下用户提交代码，帮助我们改进 SiteServer CMS ：

@liuxcoder ：建议修改：SiteServer.CMS\Core\ContentUtility.cs #1563

**Comment by lovingyou521521** [comment]
你好，请问一下，未来会有规划论坛插件吗？类似Discuz的基础功能，谢谢！

**Comment by drsonic192** [comment]
除了API 密钥，还能够以管理员身份及以用户身份访问REST Api

这个的使用说明是不是还没有更新到API的文档中？

**Comment by dingduv** [comment]
1、后台多个表单如何引用，没有官方文档（未找到相关文档），默认引用最后一个表单；
2、表单提交未过滤<html、<script ,前台可提交任何形式的<html、<script ，后台都按照<html、<script 语法显示，严重影响网站安全；
3、表单数据浏览无法关闭，
网址/SiteFiles/Plugins/SS.Form/templates/list1/index.html?siteId=&formId=&apiUrl=%2Fapi，任何人知道siteID、formID，无需登录管理后台，均可打开浏览表单数据，存在数据泄露风险。

**Comment by gamediy** [comment]
asp.net core版本什么时间出来？

**Comment by lcgtpr** [comment]
还是希望把以前版本中的流量统计功能再推出出来，越来越多的客户都希望在网页里自动显示网站的访问量，以前版本的功能就很方便，现在新版本都没有这个功能，第三方插件又很难实现这效果，都不敢用新版了

**Comment by hanpanapn** [comment]
> 你好，请问一下，未来会有规划论坛插件吗？类似Discuz的基础功能，谢谢！

来来，我们一起搞一个^^

**Comment by drsonic192** [comment]
更新最新版本后在后台无法正常增加栏目，打开数据库（Sqlserver）后发现保存的栏目的siteid值为0

**Comment by starlying** [comment]
更新最新版本后在后台无法正常增加栏目这个问题已解决，关注一下后台升级，近期会发布更新补丁 @drsonic192

**Comment by qqyule** [comment]
#1550 修复了吗？  我生成了页面显示的还是英文账号呀
