### ISSUE TITLE
2019年1月/2月迭代计划

### ISSUE THREAD

**Issue by starlying** [siteserver/cms#1683]
欢迎来到2019年3月4日发布的SiteServer CMS 新版本 V6.9，经过两个月的连续迭代开发，V6.9 版本新增了几项重要功能，我们希望你会喜欢，一些关键的亮点包括：

## BUG修复

* [x] 管理员是否可以查看其他人添加的内容 设置无效. #1724
* [x] SQL SERVER 2008 版本数据库startNum不起作用 #1674
* [x] 后台发文必填项BUG #1715
* [x] 表单插件回复后还是显示未回复状态 #1704 
* [x] 密码规则设置带有符号，无法重置密码 #1699
* [x] 生成管理中栏目与内容无法全选 #1698
* [x] 输入http://localhost:99/siteserver/出现登录页面而不是安装向导 #1694
* [x] 如果副标题的开头是"--"则发布后会被替换成“_sqldoulbeline_” #1333
* [x] 互动交流插件BUG #1348
* [x] /api/pages/settings/adminAccessTokens?&1536654977155 #1332
* [x] 互动交流 设置为 不公开， 为什么前台还是公开的？ #1372
* [x] 翻页实体标签TotalNum失效了 #1306
* [x] 互动交流栏目如何调用答复内容 #1411
* [x] API的trigger地址可以跳转到站外页面 #1373

## 功能增强

* [x] 自定义用户中心登录/注册界面背景图
* [x] 开发插件时同一个插件没法添加多个一级菜单 #1695
* [x] 建议系统在线站点模板显示模板缩略图 #1650
* [x] 优化用户中心加载速度 #1003
* [x] 后台用户管理应该显示用户头像 #1103

## 贡献

感谢以下用户提交代码，帮助我们改进 SiteServer CMS ：

@liangminhua ：IE浏览器不能正确解析对象属性缩写 #1754

**Comment by shuomeng** [comment]
这个系统从以前的3.6.5升级到开源版本后，会员系统功用就废了。快两年了，一直处在停滞状态。实在受不了了，准备换用别的系统。

**Comment by CiChui** [comment]
还是没说什么时候出Core版

**Comment by xiaodai945** [comment]
会员功能太鸡肋了，目前只有投稿功能，建议添加更多会员自定义功能，加油！！！

**Comment by sudons** [comment]
建议将主站点文件和子站点文件分目录放在安装目录下的壹个统壹文件夹下面！还有那些T开关的模板文件建议英文名！

**Comment by 77528395** [comment]
阿里OSS功能能加入计划吗？等的花儿都谢了

**Comment by wsnsnsns** [comment]
> 阿里OSS功能能加入计划吗？等的花儿都谢了

顶一个~

**Comment by namehou** [comment]
论坛问题没人回复啊   用你们这个软件有个问题都找不到一个平台解决  github 贴吧  没人回复，QQ群好不容易有个回复，让重新安装一遍，还是没有解决问题

**Comment by zfnet0591** [comment]
> 论坛问题没人回复啊 用你们这个软件有个问题都找不到一个平台解决 github 贴吧 没人回复，QQ群好不容易有个回复，让重新安装一遍，还是没有解决问题

建议官方还是搭建一个产品论坛吧。可以方便用户对产品的使用交流。github还是纯技术一点比较好。

**Comment by liangminhua** [comment]
> 还是没说什么时候出Core版

有什么意义呢？如果不在Windows部署用Mono不就可以嘛。

**Comment by vvvcnc** [comment]
请问6.9版本出来了吗？我看更新计划写的是2019年3月1日发布的。

**Comment by greatvpn** [comment]
什么时候可以出Net Core版本 很期待

**Comment by tiandao-dongguan** [comment]
.NET Core版的直接抛弃STL改用RazorPages.
