### ISSUE TITLE
2019年3月/4月迭代计划

### ISSUE THREAD

**Issue by starlying** [siteserver/cms#1790]
这个计划包含我们2019年3月/4月的工作。这是一个8周的迭代计划，我们将在2019年5月1日号发布 SiteServer CMS V6.10正式版。

**SiteServer CMS V7 版本将全面支持.NET Core，正在逐步开发测试中，预计2019年7月将发布预览版， V6.10版本只修复现有系统的BUG，新增功能将移至V7版本。**

> **提示：** 此文档会持续修订，新发现的bug以及需要完善的功能会实时更新至此文档。

> **提示：** 此文档中列举的项目只表示我们承诺会实现且优先安排，并不代表迭代能够全部实现。

## 计划安排
2019-05-01：发布 SiteServer CMS 6.10 正式版

## BUG修复

* [ ] 内容复制时选择引用地址或者引用内容时和完全复制效果一样 #1860
* [x] 用户组删除时，【确定】按钮显示有问题 #1859
* [x] 提交表单插件偶尔出现无法输入问题 #1825
* [x] 样式文件管理修改文件夹名称后页面报错 #1823 
* [x] 插件API中ContentDeleteCompleted触发函数，内容删除的时候未触发 #1808
* [x] 使用新增内容API添加内容时，远程服务器返回错误: (500) 内部服务器错误 #1389 
* [x] API接口请求 当前栏目无法获取子栏目及子栏目以下内容 #1806
* [x] 内容相册 复制到其它栏目时，内容相册内容为空 #1805 
* [x] 升级6.9.0后插件表单的数据查看功能不显示了 #1819
* [x] 内容页[SITESERVER_PAGE]分页失效 #1414
* [ ] 如果IIS_IUSRS没有根目录的修改权限，系统无法升级 #1789
* [ ] 后台隐藏的字段，在用户中心投稿里没有被隐藏 #1647
* [ ] 站点链接 边上的 站点列表显示顺序反了 #1570
* [x] 投票，引用js 路径错误 #1586 
* [ ] 跨站点复制新闻内容时正文中的图片没有跨站点复制过去 #1305
* [x] 【投票】后台勾选提交投票者信息，前台页面没有显示  #190
* [ ] 图片删除的时候应该把相应物理路径的图片一起删除 [#4](https://github.com/siteserver/SS.Photo/issues/4)。
* [x] 投票字段管理，复选列表,单选列表,下拉列表,---快速设置失效。 #1123 
* [ ] 角色分配给管理员时，一个账号一个角色没有问题，一个账号多个角色有问题 #1327 
* [ ] 站点之间的栏目或内容转移图片路径问题。 #1346
* [x] 在内容模板中，将文章内容设置成分页 #1383
* [ ] 引用内容不同步 #1443
* [ ] There is a vulnerability that the attacker can uploads a file bypassed the filtering rule to getshell. #1858

## 功能增强

* [x] MySQL 8.0 Retrieval of the RSA public key is not enabled for insecure connections. #1615
* [x] 附件下载标签完善 #1826
* [x] 提交表单插件——字段管理导入导出 #466
* [x] 提交表单插件——新增日期格式及时间格式 #466
* [x] 删除栏目时栏目下的内容应该进入回收站，而不是直接删除，以便恢复数据 #1807
* [ ] 建议模板列表页搜索功能加上搜索提示，显示可能的模板 #985
* [ ] 文章url地址增加按guid来生成 #1101 
* [ ] stl:if 判断自定义内容 #1135 
* [ ] 字段设置中内置字段的“添加”建议改成“修改” #1148 
* [ ] 后台内容搜索的目标字段没有“内容” #1157 
* [ ] API附加字段取值建议 #1161
* [ ] 模板点击修改后应该返回之前的列表 #1180 
* [ ] 在html编辑状态修改后点“确定”不会保存 #1181 
* [ ] 一个星期内有登录自动顺延 #1201
* [ ] stl:if 支持testOperate="startsWith"判断字符开始 #1248
* [ ] 建议！在用户注册的时候，可以选择用户组，方便分类发布投稿 #1287 
* [ ] 在后台的在线编辑器里插入视频后 如何进行循环播放设置 #1296
* [ ] 生成单页模板特别多，建议可以设置单页文件夹，将文件夹内的单页统一生成 #1309 
* [ ] 关于生成管理下的一键生成的建议 #1400
* [ ] 关于 用户投稿设置 里面 关联用户 问题。 #1399 

## 待验证

* [ ] 编辑器里li标签加不了class #1649
* [ ] CLI命令行备份并升级还原 3.64到6.76(在线升级到最新的)出问题 #1575
* [ ] <stl:contents>标签带条件时startNum不起作用 #1539
* [x] 6.7.1，表单代码嵌入到页面中不能使用 #1580
* [ ] 还拟字段的问题，你们说升级后增加了判断功能，请解答一下！ #1582
* [ ] 希望SiteServer在下一个版本增加的功能 #1510 
* [ ] stl:photo标签解析错误BUG #1506
* [ ] <stl:channel type='content'></stl:channel>标签bug #1463
* [ ] 跨站转发后的页面不会生成静态页面 #1554
* [ ] 导入word生成html BUG，一些文档保存不了。 #1018
* [ ] 用户中心问题 #1150
* [ ] Server Error in Application 未将对象引用设置到对象的实例。 #1163
* [ ] 新版本无法读取站点模板，版本号：Siteserver-6.5.1.0 #1160 
* [ ] 相册插件，想加图片，出现这个提示 #1212
* [ ] 图片同步问题 #1240 
* [ ] <stl:search>当搜索关键词为空的时候，怎么不显示内容啊？ #1253 
* [ ] Table 'xxxxxxx.siteserver_table' doesn't exist #1275
* [x] SS.Photo 插件找不到方法 #1314
* [ ] 6.6.1版本，内容变动，引用内容无变化不同步 #1325 
* [x] 提交表单在点击回复时不出现编辑器无法编辑 #1340
* [ ] 更新10天内内容以红色突出无效 #1347
* [ ] 互动交流无法提交表单 #1344
* [ ] 6.6.20-beta 生成页面有问题 #1358
* [x] 插件ss:poll生成问题 #1362

**Comment by shitouyu** [comment]
新建站点时.建议恢复到可以选择上级站点选项.方便直接成生站点目录文件在上级目录下.现在我们几十个站点在跟目录下.上级目录下也有这些站点的目录.管理很不方便.或者转移站点到下级目录时.把根目录下的站点目录删除或转移到上级目录下.不要重复在根目录下也有.谢谢

**Comment by sscmscom** [comment]
![image](https://user-images.githubusercontent.com/40627774/53709466-6baa6100-3e73-11e9-82d3-9544ddc90252.png)

这里不是有选择上级站点功能吗？@shituoyu

**Comment by china-live** [comment]
有一个建议，.NET Core版的直接抛弃STL改用RazorPages代替可好。

**Comment by shitouyu** [comment]
> ![image](https://user-images.githubusercontent.com/40627774/53709466-6baa6100-3e73-11e9-82d3-9544ddc90252.png)
> 
> 这里不是有选择上级站点功能吗？@shituoyu



为何我的是这样的?????

![image](https://user-images.githubusercontent.com/43244277/53716655-90610180-3e90-11e9-948c-84929c0b39c2.png)

**Comment by shitouyu** [comment]
> ![image](https://user-images.githubusercontent.com/40627774/53709466-6baa6100-3e73-11e9-82d3-9544ddc90252.png)
> 
> 这里不是有选择上级站点功能吗？@shituoyu

已找到原因.解决了.谢谢

**Comment by cpwph** [comment]
6.90版本没有得选择，要在那里设置吗？你们用的是那个版本呢？
![qq 20190308090728](https://user-images.githubusercontent.com/35787388/54000363-06f84a80-4182-11e9-9756-b1670f000a81.png)

**Comment by liuxyxh** [comment]
坐等SiteServer CMS V7 .NET Core版本

**Comment by tiandao-dongguan** [comment]
> 有一个建议，.NET Core版的直接抛弃STL改用RazorPages代替可好。

看来还是有懂行情的兄弟，STL早就该换RazorPages，RazorPages目前也支持.net core.

**Comment by linyx2001** [comment]
能开发个公众号插件就完美了

**Comment by lemonmonster** [comment]
表单插件修复来一个好吗？秋梨膏

**Comment by easy0113** [comment]
能离线升级吗

**Comment by nhren** [comment]
哈哈，喜欢Razor模板

**Comment by xcdiv** [comment]
STL还可以，不过推荐增加<stl:rand min="1" max=“999”/>这样的标签增加随机数，另外stl嵌套如何输出JSON？
