### ISSUE TITLE
2018年3月迭代计划

### ISSUE THREAD

**Issue by starlying** [siteserver/cms#300]
# 2018年3月迭代计划
这个计划包含我们2018年三月份的工作。这是一个4周的迭代计划，我们在4月1日号发布 SiteServer CMS V6.1正式版。

## 计划安排
2018-04-01：发布 SiteServer CMS 6.1 正式版

## BUG修复
* [x] 用户中心用户无法投稿 #251
* [x] 系统无法部署在其他站点的应用程序下 #289  #318
* [x] 表单必须启用验证，不然会提示输入验证码 #288
* [x] Oracle安装后使用模板创建站点出现表或视图不存在 #298
* [x] Oracle安装后创建站点的时候不能选择指定辅助表 #297
* [x] 后台锁定或者删除管理员时提示404错误 #319
* [x] 支付集成设置中配置参数时提示未授权访问
* [x] 已审核通过的文章，状态改为待审核，静态页还存在 #204  #63
* [x] 栏目管理显示项不起作用  #171
* [x] 栏目管理——跨站转移栏目后，该栏目下内容图片打开失败	 #170
* [x] 子站单独部署绑定域名表单提交存在跨域问题	 #93
* [x] 内容编辑器上方的【插入视频】按钮有问题	 #116
* [x] 关于stl:value isReturnToBr=“true"回车不会自动换行	 #138
* [x] channel 标签 isLower、isUpper、isReturnToBr属性不起作用	 #141
* [x] action标签 AddFavorite 属性不起作用	 #140
* [x] 栏目管理的生成没起效果，也没有像内容管理的生成一样提供弹出提示框  #172
* [x] 【表单】表单管理中的上下排序无效。  #179
* [x] 辅助表管理——虚拟字段管理——页面乱码  #214
* [x] stl:count统计内容数会包含草稿和待审核内容  #244
* [x] 跨站转发设置——当选择需要提示时——没有提示，转发也失败  #216
* [x] 购物流程走不通，点击购买，购物车金额为0  #328
* [x] 跨站转发的向所有站点转发内容设置无效  #330
* [x] 批量转移内容后页面没有跳转，没有提示转移成功  #335
* [x] The path is not of a legal form #355
* [x] 在内容管理列表页点击表单管理，屏幕尺寸不够的情况下显示不全 #357
* [x] 自定义表单插件单选及多选必填项不起作用 #366
* [x] API独立部署后，后台内容无法上传图片 #372
* [x] 已保存内容点击预览会出现一条该内容的审核信息 #381
* [x] 上传附件时如果文件名含as字符，将会被删掉 #382
* [x] ueditor超链接保存到数据库中加前缀@的Bug #384 
* [x] ueditor 解析excel图标不正确 #390
* [x] 互动交流和信息公开的数据统计分析报错（Oracle数据库） #392
* [x] 调查问卷标题在手机端显示，行间距太紧 #409

## 功能增强
* [x] 优化用户中心插件前台页面加载速度 #277
* [x] 系统文件压缩，删除遗留文件，将安装包大小压缩至原来一半
* [x] 栏目列表查询从数据库放入缓存中，提升系统反应速度
* [x] 系统提示方式不统一 #354
* [x] 编辑器无法添加优酷视频 #356 
* [x] 包含标签能够自定义参数 #377 
* [x] 内容列表显示项没有添加时间 #396

## [电子政务信息公开插件（SS.GovPublic）](https://github.com/siteserver/GovPublic)
* [x] 信息采集
* [x] 信息管理
* [x] 信息审核
* [x] 分类法管理 
* [x] 索引号生成规则
* [x] 可选择部门设置
* [x] 信息公开设置
* [x] 重新生成索引号
* [x] 主动信息公开统计

## [电子政务互动交流插件（SS.GovInteract）](https://github.com/siteserver/SS.GovInteract)
* [x] 待受理办件
* [x] 待办理办件
* [x] 待审核办件
* [x] 所有办件
* [x] 新增办件
* [x] 互动交流分类
* [x] 负责部门设置
* [x] 负责人员设置
* [x] 办件字段管理
* [x] 办件提交样式
* [x] 办件查询样式
* [x] 邮件/短信发送管理
* [x] 办件类型管理
* [x] 办件预警设置
* [x] 互动交流设置
* [x] 互动交流统计

**Comment by LiYuerong** [comment]
论坛怎么打不开？

**Comment by starlying** [comment]
论坛迁移至 GitHub Issues了：
http://www.siteserver.cn/bbs/index.html

**Comment by LiYuerong** [comment]
那把官方网站的论坛链接改下吧，现在是跳到bbs.siteserver.cn了。

**Comment by starlying** [comment]
对，谢谢提醒

**Comment by mrcou** [comment]
电子政务信息公开插件（SS.GovPublic）电子政务互动交流插件（SS.GovInteract）在哪里可以下载或者是购买？
