### ISSUE TITLE
2018年4月迭代计划

### ISSUE THREAD

**Issue by starlying** [siteserver/cms#412]
# 2018年4月迭代计划
这个计划包含我们2018年四月份的工作。这是一个4周的迭代计划，我们将在5月1日号发布 SiteServer CMS V6.2 正式版。

> **提示：** 此文档会在本月持续修订，新发现的bug以及需要完善的功能会实时更新至此文档。

> **提示：** :running_man:代表正在进行中的开发。

## 计划安排
2018-05-01：发布 SiteServer CMS 6.2 正式版

## BUG修复
* [x] 系统站点管理中替换模板，后台栏目中数据为空 #237
* [x] stl:search 标签搜索问题  #147 
* [x] stl:search中的{request.word}不解析 #28
* [x] 内容导入导出问题  #166
* [x] 站点数据统计里面的管理员工作量统计，无法使用日期筛选功能  #74
* [x] 辅助表管理——真实字段管理——原有真实字段不能排序  #213
* [x] 【基本使用】 栏目管理中导入栏目失败  #198
* [x] 用户中心投稿审核问题  #13
* [x] 日志阈值设置站点日志不起作用  #210
* [x] 运用了，groupChannel之后，upLevel 和 topLevel 无效  #58
* [x] 附件下载量排名是按照Taxis排序的，没有按下载量排名  #64
* [x] 独立部署站点编辑带图片的文章后，图片无法显示  #321
* [x] 文章跨站转发后图片地址错误  #320
* [x] 栏目删除失败、栏目导入压缩包（从系统里导出来的）失败  #168
* [x] 在使用search时pagecontents报错：列名 'TAXIS' 无效 #369
* [x] 【Oracle】使用模板创建站点提示 并非所有变量都已绑定  #334
* [x] 子站点设置独立域名，上传图片时路径被加子目录名，导致二级域名访问图片不显示 #425 #470
* [x] 模板管理中生成页面功能只能生成文件模板类型 #477
* [x] 字数超出最大允许值，服务器可能拒绝保存！ #397 
* [x] 服务器无法在已发送 HTTP 标头之后设置状态。 #484
* [x]  非超级管理员可以运行升级向导 #485
* [x]  在地址栏输入没有的.aspx文件会自动跳转到后台目录的错误页，暴露后台地址 #485
* [x] 后台的文章搜索没有标题选项 #494
* [x] Mysql新建站点栏目乱码 #511

## 功能增强
* [x] 此网页包含重定向循环 #358
* [x] 可自定义表单提交成功 #367
* [x] 简化表单插件自定义模板功能，直接使用html #478
* [x] 内容列表翻页优化 #487
* [x] 管理员日志、用户日志、系统错误日志均有禁用日志功能，唯独站点日志没有 #510 
* [x] 系统升级增加数据库字段一致性验证、同步功能
* [x] 系统判断是第一次安装还是数据库无法连接，分别跳转至安装界面与报错界面 #473

## 专题功能
* [x] 实现专题增删改查
* [x] 实现专题STL解析
* [x] 集成专题生成至生成管理中

## 老版本升级
* [x] 支持3.6版本（3.6、3.6.1、3.6.2、3.6.3、3.6.4）升级至最新版本
* [x] 支持4.0版本升级至最新版本
* [x] 支持4.1版本升级至最新版本
* [x] 支持5.0版本升级至最新版本

## siteserver.exe命令行
* [x] 实现备份命令：siteserver backup
* [x] 实现恢复命令：siteserver restore
* [x] 实现系统升级命令：siteserver update
* [x] 实现版本查看命令：siteserver version

**Comment by china-live** [comment]
提交一个不是bug的bug，为了方便描述，假设需要格式化的时间是2000年2月1日。
用<stl:content type="AddDate" formatString="d"></stl:content>
取出来的并不是“1”（按文档的说法是月份中的某一天，一位数的日期没有前导零），而是短日期“2000/2/1”。
如果是<stl:content type="AddDate" formatString="dd"></stl:content>
测可以正确取出“01”
猜测其他单字母，比如M或y也会有这种问题。

**Comment by starlying** [comment]
好的。我们会把格式化的文档完善一下

**Comment by vcvcvcvcvcvcv** [comment]
转贴央视视频提示“无法获取视频id“

**Comment by qiang12300** [comment]
希望完善一个前端和后台的部署和发布的详细教程的文档

**Comment by starlying** [comment]
好的，我们会尽快安排
