### ISSUE TITLE
 2018年6月迭代计划

### ISSUE THREAD

**Issue by starlying** [siteserver/cms#719]
这个计划包含我们2018年六月份的工作。这是一个4周的迭代计划，我们将在7月1日号发布 SiteServer CMS V6.4 正式版。

> **提示：** 此文档会在本月持续修订，新发现的bug以及需要完善的功能会实时更新至此文档。

> **提示：** 此文档中列举的项目只表示我们承诺会实现且优先安排，并不代表本月迭代能够全部实现。

## 计划安排
2018-07-01：发布 SiteServer CMS 6.4 正式版

## 内容筛选插件

* [x] 针对栏目开启/关闭内容筛选功能
* [x] 筛选字段设置
* [x] 内容筛选自定义样式

## REST 管理员API

* [x] [新增管理员API](https://docs.siteserver.cn/api#/administrators/create)
* [x] [修改管理员API](https://docs.siteserver.cn/api#/administrators/update)
* [x] [删除管理员API](https://docs.siteserver.cn/api#/administrators/delete)
* [x] [获取管理员API](https://docs.siteserver.cn/api#/administrators/get)
* [x] [获取管理员列表API](https://docs.siteserver.cn/api#/administrators/list)
* [x] [管理员登录API](https://docs.siteserver.cn/api#/administrators/login)
* [x] [退出登录API](https://docs.siteserver.cn/api#/administrators/logout)
* [x] [修改密码API](https://docs.siteserver.cn/api#/administrators/resetPassword)

## REST 用户API

* [x] [新增用户API](https://docs.siteserver.cn/api#/users/create)
* [x] [修改用户API](https://docs.siteserver.cn/api#/users/update)
* [x] [删除用户API](https://docs.siteserver.cn/api#/users/delete)
* [x] [获取用户API](https://docs.siteserver.cn/api#/users/get)
* [x] [获取用户API](https://docs.siteserver.cn/api#/users/getAvatar)
* [x] [上传用户头像API](https://docs.siteserver.cn/api#/users/updateAvatar)
* [x] [获取用户列表API](https://docs.siteserver.cn/api#/users/list)
* [x] [用户登录API](https://docs.siteserver.cn/api#/users/login)
* [x] [修改密码API](https://docs.siteserver.cn/api#/users/resetPassword)
* [x] [新增用户操作日志API](https://docs.siteserver.cn/api#/users/createLog)
* [x] [获取用户操作日志API](https://docs.siteserver.cn/api#/users/getLogs)

## REST 验证码API
* [x] [获取验证码图片API](https://docs.siteserver.cn/api#/captcha/get)
* [x] [验证验证码API](https://docs.siteserver.cn/api#/captcha/check)

## BUG修复

* [x] MySql 使用backup备份命令报错 #543
* [x] 内容空格解析BUG #786
* [x] 解决在切换用户登录时，顶部菜单显示的用户名不变的问题 PR #761
* [x] 互动交流插件 →待受理办件 点击受理按钮报错 #784
* [x] 预览页面代码错误导致单页模板的标签未解析 #835
* [x] MYSQL 创建内容表默认字符集是latin1，需要改成utf8 #843 
* [x] ORACLE 管理员管理里面 还有有_EMPTY_ #881
* [x] 后台修改代码的时候，行号和代码对不齐 #940 

## 功能增强

* [x] 为后台栏目树中的首页和外链栏目添加图标  PR #756
* [x] 生成文件后缀为index.html时应该省略文件名 #853
* [x] 设置了独立api地址，没同步管理员cookie，导致授权失败 #873
* [x] 设置独立API后，如果后台与API地址是不同的根域名，访问API返回未授权 #909
* [x] 后台管理员登录密码没有加密传输 #911

## 贡献

感谢以下用户提交代码，帮助我们改进 SiteServer CMS ：

@player2135：解决在切换用户登录时，顶部菜单显示的用户名不变的问题 PR #761
@xelnage：为后台栏目树中的首页和外链栏目添加图标 PR #756 
@leonedit：后台修改代码的时候，行号和代码对不齐 #940

**Comment by shuomeng** [comment]
mysql数据库的5.0版想要升级6.2或6.3看来又没希望了。

**Comment by starlying** [comment]
mysql数据库5.0升级最新版本已经支持了，通过CLI命令行可以升级

**Comment by zzj19930721** [comment]
6月用户注册API解决， 可以尝试商城购物模块了

**Comment by starlying** [comment]
对，我们会尽快修复@shuomeng

**Comment by zzj19930721** [comment]
@starlying  哥们，/api/v1/stl/channels 这个翻页功能还没解决吗
