### ISSUE TITLE
2018年7月迭代计划

### ISSUE THREAD

**Issue by starlying** [siteserver/cms#956]
这个计划包含我们2018年七月份的工作。这是一个4周的迭代计划，我们将在8月1日号发布 SiteServer CMS V6.5 正式版。

> **提示：** 此文档会在本月持续修订，新发现的bug以及需要完善的功能会实时更新至此文档。

> **提示：** 此文档中列举的项目只表示我们承诺会实现且优先安排，并不代表本月迭代能够全部实现。

## 计划安排
2018-08-01：发布 SiteServer CMS 6.5 正式版

## 完善插件
* [x] 完成SiteServer.Plugin项目所有类与方法的注释。
* [x] SiteServer.Plugin 支持 .NET Core。
* [x] 发布稳定版本SiteServer.Plugin插件开发库。
* [x] 新增SiteServer Cli命令行插件支持。
* [x] 插件REST Api授权支持。

## 完善Cli命令行
* [x] 将所有的命令执行方式改为异步方式，提升命令执行速度。
* [x] 实现命令行按计划不间断执行功能。

## REST 内容API

* [x] 新增内容（内容投稿）API
* [x] 修改内容API
* [x] 删除内容API
* [x] 获取内容API
* [x] 获取内容列表API

## BUG修复

* [x] 内容管理，点击显示项，然后报错。SqlServer 版本 #960 
* [x] 生成后的静态页面强制有Jquery文件引用，无法去掉。 #1010
* [x] 新版本用户中心插件点击进去一直加载 #991
* [x] 添加脚本文件的时候脚本文件名。不能有文件扩展名 有问题， #1026
* [x] 投票插件投票截止日期不设置无法使用投票 #945
* [x] Server Error in Application 无法将类型为“System.Data.DataRowView”的对象强制转换为类型“System.Data.IDataRecord”。 #1033
* [x] 使用二级域名作为后台地址后登出后仍然可以访问后台 #1037
* [x] 后台用户管理中禁止注册新用户了，用户中心那里仍然可以顺利注册 #1043
* [x] 添加自定义表单插件后，提示运行错误 #1056 
* [x] 信息公开插件里信息审核点击后提示错误 #1059 
* [x] 内容回收站能打开了，但是不能清空和删除 #1062
* [x] stl:login登录和stl:register注册提示“请求的资源不在服务器上” #975
* [x] 栏目管理中复选框无法正常勾选 #1072
* [x] 在回收站点击删除后，内容标题不显示 #1092
* [x] 模板编辑中，对代码应用格式按钮点击没效果 #1097
* [x] 新版本虚拟字段新增不保存，第二次编辑才能保存 #1104 
* [x] 内容里面插入腾讯视频，无法播放 #1079
* [x] 建议siteserver支持央视视频转贴并播放 #1040

## 功能增强

* [x] 建议include、css、js文件夹可设置更改位置 #575 
* [x] 内容列表数据少时应该隐藏底部按钮 #978
* [x] 筛选插件后台添加前台标签样式生成功能 #1016 
* [x] 互动交流插件后台添加前台标签样式生成功能 #1017
* [x] 权限分配时将系统权限与插件权限分开 #1034
* [x] 插件安装需要增加失败检查，让系统再下载一次 #1045 
* [x] 插件一键升级功能 #727
* [x] 只要不退出用户登录，重新打开后台都可进入 #1077
* [x] 内容筛选插件，应该可以设置默认内容 #1094
* [x] 栏目管理的选中问题 #1120
* [x] 将MYSQL数据库默认字符集由utf8修改为utf8mb4 #843

## 待验证
* [x] 图片相册插件无法解析出相应图片 #1025
* [x] 内容里面插入腾讯视频，无法播放 #1079

**Comment by vcvcvcvcvcvcv** [comment]
仍然没有看见支持央视视频转贴并播放的迹象，几个朋过去了，是不是没有希望支持央视视频转贴并播放了？

**Comment by vcvcvcvcvcvcv** [comment]
还是没有希望支持央视视频转贴并播放，很奇怪！是不是SiteServer CMS与央视有约定不转播放央视视频？如果是这样，我们只好放弃SiteServer CMS了，等了几个月仍然没有看见解决的希望！

**Comment by puzhengwu** [comment]
啥时候能移植到.net care，可跨平台布署

**Comment by 17671877** [comment]
正在进行中，.net core不支持aspx页面，目前正在逐步将页面迁移至cshtml格式

**Comment by aidchome** [comment]
早在很久前就提到有增加云存储的功能，这都过去一年了 还是没有消息！

**Comment by qqyule** [comment]
广告插件什么时候上线啊  需求很大

**Comment by KevinPan** [comment]
广告插件现在有了吗
